### ISSUE TITLE
Google slides opening in separate window

### ISSUE THREAD

**Issue by ColbyReinhart** [JMANN240/cof-2021#20]
Google slides opens in a separate window when opening it from the "google" button. This may be the case for all of the google suite applications when navigated to from drive.google.com instead of their respective types, such as docs.google.com. More testing needed. JT suspects it happens because the target is trying to open these in a new tab.

**Comment by ColbyReinhart** [comment]
A new window opens from drive.google.com and not slides.google.com because drive opens it with target=_blank. Try this code:

`
win.webContents.on('new-window', (event, url) => {
    event.preventDefault()
    win.loadURL(url)
})
`

**Comment by JMANN240** [comment]
Fixed by commit [ddf00cd](https://github.com/JMANN240/cof-2021/commit/ddf00cd9c638d38ae4263ed2945ad8c9fc6c609a)
